-- ARIA Phase 2 — conversation memory tables.
--
-- 1. `aria_conversation_summaries` (1:1) holds a compacted summary of
--    the messages that have aged out of the 40-message verbatim
--    window. Regenerated by `aria.service` whenever the window slides
--    past `covers_through_message_id`.
-- 2. `aria_conversation_memory` (1:N) holds key/value facts pinned by
--    a background extractor after each assistant reply. Re-injected
--    into every system prompt for the same conversation.
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS "aria_conversation_summaries" (
  "conversation_id"            UUID         PRIMARY KEY,
  "summary"                    TEXT         NOT NULL,
  "covers_through_message_id"  UUID         NULL,
  "message_count"              INTEGER      NOT NULL DEFAULT 0,
  "model"                      TEXT         NOT NULL,
  "created_at"                 TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"                 TIMESTAMP(3) NOT NULL,
  CONSTRAINT "aria_conversation_summaries_conversation_id_fkey"
    FOREIGN KEY ("conversation_id") REFERENCES "aria_conversations"("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "aria_conversation_memory" (
  "id"               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "conversation_id"  UUID         NOT NULL,
  "key"              TEXT         NOT NULL,
  "value"            TEXT         NOT NULL,
  "created_at"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"       TIMESTAMP(3) NOT NULL,
  CONSTRAINT "aria_conversation_memory_conversation_id_fkey"
    FOREIGN KEY ("conversation_id") REFERENCES "aria_conversations"("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "aria_conversation_memory_conversation_id_key_key"
  ON "aria_conversation_memory" ("conversation_id", "key");
CREATE INDEX IF NOT EXISTS "aria_conversation_memory_conversation_id_idx"
  ON "aria_conversation_memory" ("conversation_id");
