-- Configurable investor type / category options + best-effort re-tag
-- of existing investors from the TBH Pipeline Master sheet.
-- Idempotent: CREATE IF NOT EXISTS, ON CONFLICT DO NOTHING, and the
-- re-tag only touches rows still on the 'other' fallback.

CREATE TABLE IF NOT EXISTS "investor_type_options" (
    "key" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "investor_type_options_pkey" PRIMARY KEY ("key")
);
CREATE INDEX IF NOT EXISTS "investor_type_options_sort_order_idx" ON "investor_type_options"("sort_order");

INSERT INTO "investor_type_options" ("key","label","sort_order","updated_at") VALUES
    ('family_office',         'Family Office',          0, CURRENT_TIMESTAMP),
    ('private_equity',        'Private Equity / AM',    1, CURRENT_TIMESTAMP),
    ('venture_capital',       'Venture Capital',        2, CURRENT_TIMESTAMP),
    ('corporate_vc',          'Corporate VC',           3, CURRENT_TIMESTAMP),
    ('sovereign_wealth_fund', 'Sovereign Wealth Fund',  4, CURRENT_TIMESTAMP),
    ('corporate_capital',     'Corporate Capital',      5, CURRENT_TIMESTAMP),
    ('state_capital_soe',     'State Capital / SOE',    6, CURRENT_TIMESTAMP),
    ('growth_late',           'Growth / Late Stage',    7, CURRENT_TIMESTAMP),
    ('individual',            'Individual',             8, CURRENT_TIMESTAMP),
    ('angel',                 'Angel',                  9, CURRENT_TIMESTAMP),
    ('other',                 'Other',                 10, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Normalise legacy keys onto the new canonical set.
UPDATE "investors" SET "type" = 'venture_capital' WHERE "type" = 'vc';
UPDATE "investors" SET "type" = 'corporate_capital' WHERE "type" = 'corporate';

-- Best-effort re-tag: match existing investors by name (case-insensitive)
-- against the sheet, only where still on the 'other' fallback.
UPDATE "investors" AS i SET "type" = m.t
FROM (VALUES
    ('100 Ventures','venture_capital'),
    ('ACWA Power','corporate_capital'),
    ('AD Ports Group','state_capital_soe'),
    ('ADIA','sovereign_wealth_fund'),
    ('ADNOC','state_capital_soe'),
    ('ADQ','sovereign_wealth_fund'),
    ('ADQ (via funds)','growth_late'),
    ('ADQ Growth','private_equity'),
    ('ADQ Holding','state_capital_soe'),
    ('ALEC','corporate_capital'),
    ('Abdul Latif Jameel (ALJ)','family_office'),
    ('Abraaj Group','private_equity'),
    ('Ajlan & Bros Holding','family_office'),
    ('Al Fardan Group (Family Office)','family_office'),
    ('Al Futtaim Family Office','family_office'),
    ('Al Ghurair Family Office','family_office'),
    ('Al Ghurair Group','family_office'),
    ('Al Habtoor Family Office','family_office'),
    ('Al Habtoor Group','family_office'),
    ('Al-Futtaim Group','family_office'),
    ('Alkhleef Capital','private_equity'),
    ('Apollo Global Management','growth_late'),
    ('Aramco Ventures','state_capital_soe'),
    ('Arzan Financial Group','private_equity'),
    ('Brookfield','growth_late'),
    ('Buildiyah','corporate_capital'),
    ('Crescent Enterprises','private_equity'),
    ('DIFC Authority','state_capital_soe'),
    ('Delta Partners','private_equity'),
    ('Dubai Airports','state_capital_soe'),
    ('Dubai Holding','state_capital_soe'),
    ('Dubai Investments','sovereign_wealth_fund'),
    ('EDGE Group','state_capital_soe'),
    ('EIA (Emirates Investment Authority)','sovereign_wealth_fund'),
    ('EQT Partners','private_equity'),
    ('ESPORTS World Cup Foundation','corporate_capital'),
    ('Eighties Games','corporate_capital'),
    ('Elm','corporate_capital'),
    ('Emaar Properties PJSC','sovereign_wealth_fund'),
    ('Essa Al Ghurair Family Office','family_office'),
    ('Floward','corporate_capital'),
    ('Fortress Investment Group','private_equity'),
    ('General Atlantic','growth_late'),
    ('H.H. Sheikh Ahmed bin Dalmook Al Maktoum Office','family_office'),
    ('H.H. Sheikh Ahmed bin Saeed Al Maktoum Office','family_office'),
    ('H.H. Sheikh Butti Al Ghandi Group','family_office'),
    ('H.H. Sheikh Hamdan bin Rashid Al Maktoum Office','family_office'),
    ('H.H. Sheikh Mansoor bin Mohammed Office','family_office'),
    ('HALA','venture_capital'),
    ('HUMAIN','corporate_capital'),
    ('Homz (PropTech)','corporate_capital'),
    ('HungerStation','corporate_capital'),
    ('ICD (Investment Corporation of Dubai)','sovereign_wealth_fund'),
    ('Impact46','venture_capital'),
    ('Investcorp','growth_late'),
    ('Investcorp (KSA)','private_equity'),
    ('Jada Fund of Funds','sovereign_wealth_fund'),
    ('Jadwa Investment','private_equity'),
    ('Jahez','corporate_capital'),
    ('Jihaz','corporate_capital'),
    ('Juma Al Majid Family Office','family_office'),
    ('KAUST Innovation Fund','sovereign_wealth_fund'),
    ('KHWARIZMI Ventures','venture_capital'),
    ('KKR','growth_late'),
    ('Khalaf Ahmad Al Habtoor Office','family_office'),
    ('LeanCare','corporate_capital'),
    ('Lucidya','corporate_capital'),
    ('MADO','venture_capital'),
    ('MEVP – Middle East Venture Partners','private_equity'),
    ('Ma''aden','state_capital_soe'),
    ('Ma''aden (Corporate)','corporate_capital'),
    ('Majid Al Futtaim','family_office'),
    ('Manga Productions','corporate_capital'),
    ('Merak Capital','venture_capital'),
    ('Mubadala Capital','private_equity'),
    ('Mubadala Energy','state_capital_soe'),
    ('Mubadala Investment Company','sovereign_wealth_fund'),
    ('NBK Capital','private_equity'),
    ('NHC Innovation (National Housing Co.)','state_capital_soe'),
    ('NTDP (National Technology Dev. Program)','state_capital_soe'),
    ('Ninja (Delivery)','corporate_capital'),
    ('Noon','corporate_capital'),
    ('Okadoc','corporate_capital'),
    ('Olayan Group','family_office'),
    ('Ounass','corporate_capital'),
    ('Outliers VC','venture_capital'),
    ('PIF – Public Investment Fund','sovereign_wealth_fund'),
    ('Permira Advisers','growth_late'),
    ('Phoenix Venture Partners','venture_capital'),
    ('QIA (via funds)','growth_late'),
    ('RAED Ventures','venture_capital'),
    ('RAK Investments','sovereign_wealth_fund'),
    ('RCRC Investments','state_capital_soe'),
    ('ROSHN Group','state_capital_soe'),
    ('Riyad Capital','private_equity'),
    ('Royal Commission for AlUla (RCU)','state_capital_soe'),
    ('Royal Commission for Riyadh City','state_capital_soe'),
    ('Rua Growth Fund','venture_capital'),
    ('SABIC','corporate_capital'),
    ('SABIC Ventures','state_capital_soe'),
    ('SANABIL Investments','sovereign_wealth_fund'),
    ('SDAIA (Saudi Data & AI Authority)','state_capital_soe'),
    ('SEEDRA Ventures','venture_capital'),
    ('SIDF – Saudi Industrial Development Fund','sovereign_wealth_fund'),
    ('SITE (Saudi Information Technology Co.)','state_capital_soe'),
    ('SNB Capital','private_equity'),
    ('STV (Saudi Technology Ventures)','venture_capital'),
    ('SVC – Saudi Venture Capital','sovereign_wealth_fund'),
    ('Sakan (PropTech)','corporate_capital'),
    ('Salla','corporate_capital'),
    ('Saudi Aramco','corporate_capital'),
    ('Saudi Electricity Company (SEC)','corporate_capital'),
    ('Savvy Games Group','corporate_capital'),
    ('Seha Virtual Hospital','state_capital_soe'),
    ('Shuaa Capital','private_equity'),
    ('SiFi (HealthTech)','corporate_capital'),
    ('Silicon Badia','venture_capital'),
    ('Silver Lake','growth_late'),
    ('SoftBank Vision Fund 2','growth_late'),
    ('TAQA','state_capital_soe'),
    ('TDRA','state_capital_soe'),
    ('TECOM Group','corporate_capital'),
    ('TPG Growth','growth_late'),
    ('Tamatem Games','corporate_capital'),
    ('Tasne''e (Saudi Industrial Investment)','corporate_capital'),
    ('The Kanoo Group (Family Office)','family_office'),
    ('ToYou (Logistics)','corporate_capital'),
    ('Vezeeta','corporate_capital'),
    ('Vision Investments','private_equity'),
    ('Wa''ad Investments','private_equity'),
    ('Waha Capital','private_equity'),
    ('Watar Partners','private_equity'),
    ('anb capital','private_equity'),
    ('dnata','corporate_capital'),
    ('nama ventures','venture_capital'),
    ('stc Group','corporate_capital')
) AS m(name, t)
WHERE lower(i."name") = lower(m.name) AND i."type" = 'other';
