/**
 * Atlas canonical metrics catalog v3.1 — a faithful port of `CANONICAL_METRICS`
 * and `CANONICAL_CATEGORIES` (atlas-prod/web/atlas-v4.1.html:526-527).
 *
 * GENERATED from the Atlas repo — do not hand-edit.
 *
 * 166 metrics across 16 categories. A metric is "live" only if its formula
 * evaluates against the partner's daily series without throwing — it is not a
 * stored flag, and the live count differs per partner. A substantial number can
 * never compute, faithfully reproduced here rather than silently dropped:
 *   - band() / band_inv() / count() / count_in_tier() / weighted() appear in
 *     formulas but are not functions in the evaluator (all of category L, and
 *     every composite health score).
 *   - Category N needs mau_d1/d7/d60/d90/d180/d365, which BNII does not expose.
 *   - F1/F2/F10 reference bnry_earned_fando / bnry_earned_ngage, merged away
 *     into bnry_earned_video.
 *   - The P series is prose, not the DSL, and is scoped to country/global views.
 * Those rows render as "no data", exactly as they do in Atlas.
 */

/** Catalog version this registry was ported from. */
export const ATLAS_CATALOG_VERSION = "v3.1";

export interface AtlasMetricCategory {
  id: string;
  name: string;
  order: number;
}

export interface AtlasMetric {
  id: string;
  category: string;
  name: string;
  formula: string;
  meaning: string;
  /** Health bands are free-text in Atlas; roughly half are prose, not ranges. */
  healthy: string;
  warning: string;
  critical: string;
  unit: string;
  /** Which scopes the metric applies to: global / country / workspace. */
  views: string[];
}

export const ATLAS_METRIC_CATEGORIES: AtlasMetricCategory[] = [
  { id: "A", name: "User Acquisition", order: 1 },
  { id: "B", name: "User Engagement", order: 2 },
  { id: "C", name: "Session Quality", order: 3 },
  { id: "D", name: "Retention & Loyalty", order: 4 },
  { id: "N", name: "Multi-Horizon Cohort Retention", order: 5 },
  { id: "E", name: "BNRY Earn · Volume", order: 6 },
  { id: "F", name: "BNRY Earn · Source Distribution", order: 7 },
  { id: "O", name: "Paid Revenue & Monetization", order: 8 },
  { id: "G", name: "BNRY Redeem & Outstanding", order: 9 },
  { id: "H", name: "Commerce & Transactions", order: 10 },
  { id: "I", name: "Games & Feature Engagement", order: 11 },
  { id: "J", name: "Token Economy Health", order: 12 },
  { id: "K", name: "Trends & Velocity", order: 13 },
  { id: "L", name: "Composite Health Indices", order: 14 },
  { id: "M", name: "Anomaly & Risk Detection", order: 15 },
  { id: "P", name: "Geographic Performance", order: 16 },
];

export const ATLAS_METRICS: AtlasMetric[] = [
  {
    id: "A1",
    category: "A",
    name: "Daily New Users",
    formula: "new_users_ga",
    meaning: "First-time users today",
    healthy: "Partner baseline, growing WoW",
    warning: "Flat",
    critical: "Declining 5+ days",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "A2",
    category: "A",
    name: "New User Share",
    formula: "new_users_ga / dau_ga * 100",
    meaning: "% of today's audience that's new",
    healthy: "15-40",
    warning: "5-15",
    critical: "<5 or >50",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "A3",
    category: "A",
    name: "7-Day New User Velocity",
    formula: "sum(new_users_ga, 7d)",
    meaning: "Smoothed acquisition rate",
    healthy: "Growing WoW",
    warning: "Flat",
    critical: "Declining 2 weeks",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "A4",
    category: "A",
    name: "30-Day New User Volume",
    formula: "sum(new_users_ga, 30d)",
    meaning: "Monthly acquisition",
    healthy: "Growing MoM",
    warning: "Flat",
    critical: "Declining MoM",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "A5",
    category: "A",
    name: "Day-over-Day New User Growth",
    formula: "(new_users_ga[t] - new_users_ga[t-1]) / new_users_ga[t-1] * 100",
    meaning: "Daily acquisition velocity",
    healthy: "+2 to +20 sustained",
    warning: "-5 to +2",
    critical: "<-5 sustained 5+ days",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "A6",
    category: "A",
    name: "Week-over-Week New User Growth",
    formula:
      "(sum(new_users_ga, 7d, t) - sum(new_users_ga, 7d, t-7)) / sum(new_users_ga, 7d, t-7) * 100",
    meaning: "Weekly growth rate",
    healthy: ">=5",
    warning: "0-5",
    critical: "Negative",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "A7",
    category: "A",
    name: "New-to-Repeat Ratio",
    formula: "new_users_ga / repeated_users_ga",
    meaning: "Acquisition vs retention balance",
    healthy: "0.3-0.7",
    warning: "0.1-0.3 or 0.7-1.0",
    critical: "<0.1 or >1.0",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "A8",
    category: "A",
    name: "Acquisition Acceleration",
    formula: "linear_slope(new_users_ga, 3d)",
    meaning: "Speeding up or decaying",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative sustained",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B1",
    category: "B",
    name: "Daily Active Users (DAU)",
    formula: "dau_ga",
    meaning: "Distinct users today",
    healthy: "Partner baseline, growing",
    warning: "Flat",
    critical: "Declining 7+ days",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B2",
    category: "B",
    name: "7-Day Average DAU",
    formula: "avg(dau_ga, 7d)",
    meaning: "Smoothed daily volume",
    healthy: "Growing WoW",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B3",
    category: "B",
    name: "30-Day Rolling MAU",
    formula: "mau_d30",
    meaning: "Monthly active pool",
    healthy: "Growing MoM",
    warning: "Flat",
    critical: "Declining 2+ weeks",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B4",
    category: "B",
    name: "DAU/MAU Stickiness",
    formula: "dau_ga / mau_d30 * 100",
    meaning: "Standard engagement ratio · super-app benchmark",
    healthy: ">=20",
    warning: "10-20",
    critical: "<10",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B5",
    category: "B",
    name: "Weekly Active Users (D7)",
    formula: "mau_d7",
    meaning: "Distinct users last 7 days",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B6",
    category: "B",
    name: "WAU/MAU Ratio",
    formula: "mau_d7 / mau_d30 * 100",
    meaning: "Weekly engagement intensity",
    healthy: ">=50",
    warning: "30-50",
    critical: "<30",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B7",
    category: "B",
    name: "DAU 7-day Trend Slope",
    formula: "linear_slope(dau_ga, 7d)",
    meaning: "Direction of travel",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B8",
    category: "B",
    name: "DAU Volatility (CoV)",
    formula: "stdev(dau_ga, 7d) / mean(dau_ga, 7d) * 100",
    meaning: "Stability of daily traffic",
    healthy: "<15",
    warning: "15-30",
    critical: ">30",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B9",
    category: "B",
    name: "Engaged User Index",
    formula:
      "(dau_ga * avg_session_sec * (total_homepage_views/dau_ga)) / baseline",
    meaning: "Composite engagement volume",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "B10",
    category: "B",
    name: "MAU Recovery Index",
    formula: "mau_d30 / max(mau_d30, 90d) * 100",
    meaning: "At peak or recovering?",
    healthy: ">=90",
    warning: "70-90",
    critical: "<70",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "C1",
    category: "C",
    name: "Total Homepage Views",
    formula: "total_homepage_views",
    meaning: "All homepage views today",
    healthy: ">=DAU*1.5",
    warning: "DAU*1.0-1.5",
    critical: "<DAU*1.0 (data error)",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "C2",
    category: "C",
    name: "Homepage Views per User",
    formula: "total_homepage_views / dau_ga",
    meaning: "Daily return frequency",
    healthy: ">=2.0",
    warning: "1.3-2.0",
    critical: "<1.3",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "C3",
    category: "C",
    name: "Avg Session Duration (sec)",
    formula: "avg_session_sec",
    meaning: "Per-session time",
    healthy: ">=90",
    warning: "30-90",
    critical: "<30",
    unit: "s",
    views: ["global", "country", "workspace"],
  },
  {
    id: "C4",
    category: "C",
    name: "Total Time Engaged (user-min)",
    formula: "dau_ga * (total_homepage_views/dau_ga) * avg_session_sec / 60",
    meaning: "Total user-minutes today",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "C5",
    category: "C",
    name: "Session Length Trend",
    formula: "linear_slope(avg_session_sec, 7d)",
    meaning: "Sessions getting deeper?",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "C6",
    category: "C",
    name: "Weekly Engagement Hours",
    formula: "sum(total_time_engaged, 7d) / 60",
    meaning: "Hours engaged per week",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "hours",
    views: ["global", "country", "workspace"],
  },
  {
    id: "C7",
    category: "C",
    name: "Time-per-User (daily)",
    formula: "(total_homepage_views * avg_session_sec / dau_ga) / 60",
    meaning: "Per-user daily commitment",
    healthy: ">=3",
    warning: "1.5-3",
    critical: "<1.5",
    unit: "min",
    views: ["global", "country", "workspace"],
  },
  {
    id: "C8",
    category: "C",
    name: "Session Quality Index",
    formula: "0.5*band(C3) + 0.3*band(C2) + 0.2*band(D1)",
    meaning: "Composite 0-100",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D1",
    category: "D",
    name: "Returning User Rate",
    formula: "repeated_users_ga / dau_ga * 100",
    meaning: "% of today's audience that visited before",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D2",
    category: "D",
    name: "Repeat User Count",
    formula: "repeated_users_ga",
    meaning: "Volume of returners",
    healthy: "Growing with MAU",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D3",
    category: "D",
    name: "Repeat-to-New Ratio",
    formula: "repeated_users_ga / new_users_ga",
    meaning: "Loyalty depth",
    healthy: "1.5-3.5",
    warning: "0.8-1.5 or >5",
    critical: "<0.8",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D4",
    category: "D",
    name: "MAU Month-over-Month Growth",
    formula: "(mau_d30 - mau_d30[t-30]) / mau_d30[t-30] * 100",
    meaning: "Monthly retention growth",
    healthy: ">=5",
    warning: "0-5",
    critical: "Negative",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D5",
    category: "D",
    name: "MAU:DAU Multiplier",
    formula: "mau_d30 / dau_ga",
    meaning: "Width of user pool",
    healthy: "4-8",
    warning: "8-15",
    critical: ">15",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D6",
    category: "D",
    name: "30-Day Active Velocity",
    formula: "mau_d30 - mau_d30[t-1]",
    meaning: "Daily MAU change",
    healthy: "Positive",
    warning: "0",
    critical: "Negative 3+ days",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D7",
    category: "D",
    name: "Churn Proxy (7-day DAU decline)",
    formula: "(dau_ga[t-7] - dau_ga) / dau_ga[t-7] * 100",
    meaning: "Implied weekly user loss",
    healthy: "<2",
    warning: "2-8",
    critical: ">8",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D8",
    category: "D",
    name: "Loyalty Index",
    formula: "0.5*band(B4) + 0.3*band(D1) + 0.2*band(D4)",
    meaning: "Composite retention 0-100",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D9",
    category: "D",
    name: "DAU Persistence Rate",
    formula: "min(dau_ga, 7d) / max(dau_ga, 7d) * 100",
    meaning: "How consistent is daily volume?",
    healthy: ">=75",
    warning: "50-75",
    critical: "<50",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "D10",
    category: "D",
    name: "MAU Saturation",
    formula: "mau_d30 / partner_reachable_base * 100",
    meaning: "% of addressable audience monthly active",
    healthy: ">=30",
    warning: "10-30",
    critical: "<10",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N1",
    category: "N",
    name: "D1 Active Users",
    formula: "mau_d1",
    meaning: "Active yesterday",
    healthy: "Partner baseline",
    warning: "Declining 3+ days",
    critical: "Sudden drop",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N2",
    category: "N",
    name: "D7 Active Users",
    formula: "mau_d7",
    meaning: "Active last 7 days",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N3",
    category: "N",
    name: "D30 Active Users",
    formula: "mau_d30",
    meaning: "Active last 30 days (= MAU)",
    healthy: "Growing MoM",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N4",
    category: "N",
    name: "D60 Active Users",
    formula: "mau_d60",
    meaning: "Active last 60 days",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N5",
    category: "N",
    name: "D90 Active Users",
    formula: "mau_d90",
    meaning: "Active last quarter",
    healthy: "Growing QoQ",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N6",
    category: "N",
    name: "D180 Active Users",
    formula: "mau_d180",
    meaning: "Active last half-year",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N7",
    category: "N",
    name: "D365 Active Users",
    formula: "mau_d365",
    meaning: "Active last year (LTV pool)",
    healthy: "Growing YoY",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N8",
    category: "N",
    name: "D1/D7 Stickiness",
    formula: "mau_d1 / mau_d7 * 100",
    meaning: "% of weekly users active yesterday",
    healthy: ">=25",
    warning: "15-25",
    critical: "<15",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N9",
    category: "N",
    name: "D7/D30 Stickiness",
    formula: "mau_d7 / mau_d30 * 100",
    meaning: "% of monthly users active last week",
    healthy: ">=50",
    warning: "30-50",
    critical: "<30",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N10",
    category: "N",
    name: "D30/D60 Retention",
    formula: "mau_d30 / mau_d60 * 100",
    meaning: "Month-1 audience retained at 2-month mark",
    healthy: ">=60",
    warning: "40-60",
    critical: "<40",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N11",
    category: "N",
    name: "D30/D90 Retention",
    formula: "mau_d30 / mau_d90 * 100",
    meaning: "Month-1 audience retained at 3-month mark",
    healthy: ">=45",
    warning: "30-45",
    critical: "<30",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N12",
    category: "N",
    name: "D30/D180 Retention",
    formula: "mau_d30 / mau_d180 * 100",
    meaning: "Month-1 audience retained at 6-month mark",
    healthy: ">=30",
    warning: "18-30",
    critical: "<18",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N13",
    category: "N",
    name: "D30/D365 Retention",
    formula: "mau_d30 / mau_d365 * 100",
    meaning: "Month-1 audience retained at 12-month mark",
    healthy: ">=18",
    warning: "10-18",
    critical: "<10",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N14",
    category: "N",
    name: "D90/D365 Long-Term Retention",
    formula: "mau_d90 / mau_d365 * 100",
    meaning: "Quarter-to-year retention",
    healthy: ">=35",
    warning: "20-35",
    critical: "<20",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "N15",
    category: "N",
    name: "Retention Curve AUC",
    formula: "(band(N10) + band(N11) + band(N12) + band(N13)) / 4",
    meaning: "Lifetime engagement proxy (0-100)",
    healthy: ">=40",
    warning: "25-40",
    critical: "<25",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "E1",
    category: "E",
    name: "Daily BNRY Earned",
    formula: "bnry_earned_total",
    meaning: "Total issuance today",
    healthy: "Stable per-user, growing absolute",
    warning: "Flat per-user as DAU grows",
    critical: "Declining per-user",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "E2",
    category: "E",
    name: "BNRY per Active User",
    formula: "bnry_earned_total / dau_ga",
    meaning: "Per-user issuance rate",
    healthy: "Stable ±15%",
    warning: "Drift ±15-30%",
    critical: "Drift >30%",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "E3",
    category: "E",
    name: "BNRY per Homepage View",
    formula: "bnry_earned_total / total_homepage_views",
    meaning: "Issuance density per visit",
    healthy: "Stable ±10%",
    warning: "Drift ±10-25%",
    critical: "Drift >25%",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "E4",
    category: "E",
    name: "7-Day BNRY Earn Volume",
    formula: "sum(bnry_earned_total, 7d)",
    meaning: "Weekly issuance",
    healthy: "Growing with DAU",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "E5",
    category: "E",
    name: "Earn Velocity (BNRY/min)",
    formula: "bnry_earned_total / total_time_engaged_min",
    meaning: "Tokens per user-minute",
    healthy: "Stable",
    warning: "Drifting",
    critical: "Drift >25%",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "E6",
    category: "E",
    name: "BNRY Earned per New User",
    formula: "bnry_earned_total / new_users_ga",
    meaning: "First-day earn experience",
    healthy: ">=avg user",
    warning: "<avg user",
    critical: "<50% of avg user",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "E7",
    category: "E",
    name: "BNRY Earn DoD Growth",
    formula:
      "(bnry_earned_total - bnry_earned_total[t-1]) / bnry_earned_total[t-1] * 100",
    meaning: "Daily issuance velocity",
    healthy: "±10",
    warning: "±10-25",
    critical: ">25 swing",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "E8",
    category: "E",
    name: "30-Day BNRY Issuance",
    formula: "sum(bnry_earned_total, 30d)",
    meaning: "Monthly issuance",
    healthy: "Stable per-user, growing absolute",
    warning: "Per-user declining",
    critical: "Sustained drop",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F1",
    category: "F",
    name: "Earn Share · Fando (sports video)",
    formula: "bnry_earned_fando / bnry_earned_total * 100",
    meaning: "Video content contribution",
    healthy: "15-35",
    warning: "5-15 or 35-55",
    critical: "<5 or >55",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F2",
    category: "F",
    name: "Earn Share · Ngage",
    formula: "bnry_earned_ngage / bnry_earned_total * 100",
    meaning: "Content feed contribution",
    healthy: "15-40",
    warning: "5-15 or 40-60",
    critical: "<5 or >60",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F3",
    category: "F",
    name: "Earn Share · Spin the Wheel",
    formula: "bnry_earned_stw / bnry_earned_total * 100",
    meaning: "STW contribution",
    healthy: "10-25",
    warning: "5-10 or 25-45",
    critical: ">45",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F4",
    category: "F",
    name: "Earn Share · Screen Time",
    formula: "bnry_earned_screentime / bnry_earned_total * 100",
    meaning: "Passive-time reward share",
    healthy: "5-15",
    warning: "15-30",
    critical: ">30 (farming risk)",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F5",
    category: "F",
    name: "Earn Share · Topup (paid purchase)",
    formula: "bnry_earned_topup / bnry_earned_total * 100",
    meaning: "Paid-currency on-ramp share · high = healthy paying users",
    healthy: "15-35",
    warning: "5-15 (early monetization)",
    critical: "<5 (paid layer not functioning)",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F6",
    category: "F",
    name: "Earn Share · Quest",
    formula: "bnry_earned_quest / bnry_earned_total * 100",
    meaning: "Quest contribution",
    healthy: "10-25",
    warning: "5-10",
    critical: "<5",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F7",
    category: "F",
    name: "Earn Source Diversity",
    formula: "count(sources where earn_share >= 10%)",
    meaning: "Balance of issuance",
    healthy: "4-5",
    warning: "3",
    critical: "1-2",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F8",
    category: "F",
    name: "Top Source Concentration",
    formula: "max(earn_share across sources)",
    meaning: "Is one mechanism dominant?",
    healthy: "<35",
    warning: "35-50",
    critical: ">50",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F9",
    category: "F",
    name: "Earn Share Drift (7-day)",
    formula: "max(daily share change across sources, 7d)",
    meaning: "Stability of source mix",
    healthy: "<5",
    warning: "5-15",
    critical: ">15",
    unit: "pp",
    views: ["global", "country", "workspace"],
  },
  {
    id: "F10",
    category: "F",
    name: "Free vs Paid Issuance Ratio",
    formula:
      "(bnry_earned_fando + bnry_earned_ngage + bnry_earned_stw + bnry_earned_screentime + bnry_earned_quest) / bnry_earned_topup",
    meaning: "Engagement-issued vs purchased BNRY",
    healthy: "2.0-5.0",
    warning: "1.0-2.0 or 5.0-10.0",
    critical: "<1.0 (mostly paid) or >10.0 (no paid layer)",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O1",
    category: "O",
    name: "Daily Paying Users (proxy)",
    formula: "txns_topup (assumes 1 paying user per topup transaction)",
    meaning: "Today's paying audience",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O2",
    category: "O",
    name: "Daily Paying Conversion",
    formula: "txns_topup / dau_ga * 100",
    meaning: "% of audience that paid today",
    healthy: "3-10",
    warning: "0.5-3",
    critical: "<0.5",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O3",
    category: "O",
    name: "Paying User Share (30-day)",
    formula: "sum(txns_topup, 30d) / mau_d30 * 100",
    meaning: "Monthly paid penetration",
    healthy: "8-25",
    warning: "2-8",
    critical: "<2",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O4",
    category: "O",
    name: "BNRY per Topup Transaction",
    formula: "bnry_earned_topup / txns_topup",
    meaning: "Avg purchase size in BNRY (revenue proxy)",
    healthy: "Stable ±15%",
    warning: "Drift ±15-30%",
    critical: "Drift >30%",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O5",
    category: "O",
    name: "Topup Transactions per Paying User",
    formula: "txns_topup / daily_paying_users",
    meaning: "Repeat purchase frequency",
    healthy: ">=1.2",
    warning: "1.0-1.2",
    critical: "<1.0 (data error)",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O6",
    category: "O",
    name: "Paid BNRY 30-Day Volume",
    formula: "sum(bnry_earned_topup, 30d)",
    meaning: "Monthly paid-issuance",
    healthy: "Growing MoM",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O7",
    category: "O",
    name: "Paid-to-Free Issuance Ratio",
    formula:
      "bnry_earned_topup / (bnry_earned_total - bnry_earned_topup) * 100",
    meaning: "Paid layer's share of total issuance",
    healthy: "15-35",
    warning: "5-15 or 35-55",
    critical: "<5 or >55",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O8",
    category: "O",
    name: "Access Pass + Topup Bundle Rate",
    formula: "users_with_both_AP_and_topup_30d / daily_paying_users * 100",
    meaning: "Cross-monetization depth",
    healthy: ">=25",
    warning: "10-25",
    critical: "<10",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O9",
    category: "O",
    name: "Topup Revenue Trajectory",
    formula: "linear_slope(bnry_earned_topup, 30d)",
    meaning: "Revenue momentum",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "O10",
    category: "O",
    name: "Paid Monetization Health Score",
    formula: "0.4*band(O2) + 0.3*band(O3) + 0.2*band(O5) + 0.1*band(O7)",
    meaning: "Single 0-100 monetization score",
    healthy: ">=60",
    warning: "35-60",
    critical: "<35",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G1",
    category: "G",
    name: "Daily BNRY Redeemed",
    formula: "bnry_redeemed_total",
    meaning: "Tokens spent today",
    healthy: "Grows with earn (sub-linearly)",
    warning: "Flat as earn grows",
    critical: "Falling",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G2",
    category: "G",
    name: "Redemption Rate (daily)",
    formula: "bnry_redeemed_total / bnry_earned_total * 100",
    meaning: "% of today's issuance spent",
    healthy: "30-70",
    warning: "10-30 or 70-95",
    critical: "<10 or >100",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G3",
    category: "G",
    name: "Redemption Rate (30-day)",
    formula:
      "sum(bnry_redeemed_total, 30d) / sum(bnry_earned_total, 30d) * 100",
    meaning: "Smoothed redemption",
    healthy: "30-70",
    warning: "10-30 or 70-95",
    critical: "<10 or >100",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G4",
    category: "G",
    name: "Cumulative Outstanding BNRY",
    formula: "sum(bnry_earned_total, all) - sum(bnry_redeemed_total, all)",
    meaning: "Unspent supply",
    healthy: "Growing slowly",
    warning: "Growing fast",
    critical: "Growing exponentially",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G5",
    category: "G",
    name: "Outstanding Growth Rate",
    formula: "(outstanding[t] - outstanding[t-1]) / outstanding[t-1] * 100",
    meaning: "Net flow",
    healthy: "1-2",
    warning: "2-10",
    critical: ">10/day (inflation)",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G6",
    category: "G",
    name: "Redeem Share · Emart",
    formula: "bnry_spent_emart / bnry_redeemed_total * 100",
    meaning: "% spent on marketplace",
    healthy: "50-70",
    warning: "30-50",
    critical: "<30",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G7",
    category: "G",
    name: "Redeem Share · Access Pass",
    formula: "bnry_spent_accesspass / bnry_redeemed_total * 100",
    meaning: "% on subscriptions",
    healthy: "15-35",
    warning: "5-15",
    critical: "<5",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G8",
    category: "G",
    name: "BNRY per Redeeming User",
    formula: "bnry_redeemed_total / redeeming_users_count",
    meaning: "Avg spend per redeemer",
    healthy: "Stable",
    warning: "Drifting",
    critical: "Drift >30%",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G9",
    category: "G",
    name: "Earn:Redeem Ratio",
    formula: "bnry_earned_total / bnry_redeemed_total",
    meaning: "Issuance vs spend balance",
    healthy: "1.2-2.0",
    warning: "0.8-1.2 or 2.0-4.0",
    critical: "<0.8 or >4.0",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "G10",
    category: "G",
    name: "Redemption Latency (proxy)",
    formula: "outstanding / avg(bnry_redeemed_total, 30d)",
    meaning: "Days of supply at current burn",
    healthy: "30-90",
    warning: "90-180",
    critical: ">180",
    unit: "days",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H1",
    category: "H",
    name: "Emart Transactions per Day",
    formula: "txns_emart",
    meaning: "Daily commerce volume",
    healthy: "Growing with DAU",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H2",
    category: "H",
    name: "Emart Conversion (per user)",
    formula: "txns_emart / dau_ga * 100",
    meaning: "% users transacting daily",
    healthy: "10-40",
    warning: "3-10",
    critical: "<3",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H3",
    category: "H",
    name: "Avg BNRY per Emart Transaction",
    formula: "bnry_spent_emart / txns_emart",
    meaning: "Avg basket size",
    healthy: "Stable ±20%",
    warning: "Drift ±20-40%",
    critical: "Drift >40%",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H4",
    category: "H",
    name: "Topup Transactions per Day",
    formula: "txns_topup",
    meaning: "Daily paid-currency volume (revenue events)",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H5",
    category: "H",
    name: "Topup Conversion Rate",
    formula: "txns_topup / dau_ga * 100",
    meaning: "% users topping up",
    healthy: "3-10",
    warning: "0.5-3",
    critical: "<0.5",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H6",
    category: "H",
    name: "Quest Completions per Day",
    formula: "txns_quest",
    meaning: "Quests done today",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H7",
    category: "H",
    name: "Quest Completion Rate",
    formula: "txns_quest / dau_ga * 100",
    meaning: "% users completing quest",
    healthy: "15-40",
    warning: "5-15",
    critical: "<5",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H8",
    category: "H",
    name: "Total Transactions per Day",
    formula: "txns_emart + txns_topup + txns_quest",
    meaning: "All transactional events",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H9",
    category: "H",
    name: "Transactions per Active User",
    formula: "(txns_emart + txns_topup + txns_quest) / dau_ga",
    meaning: "Avg actions per user",
    healthy: ">=1.0",
    warning: "0.4-1.0",
    critical: "<0.4",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H10",
    category: "H",
    name: "Transaction Concentration",
    formula: "max(channel txns) / total_txns * 100",
    meaning: "Channel dominance",
    healthy: "<50",
    warning: "50-70",
    critical: ">70",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H11",
    category: "H",
    name: "Emart-to-Topup Ratio",
    formula: "txns_emart / txns_topup",
    meaning: "Commerce vs paid-currency mix",
    healthy: "1.5-5.0",
    warning: "0.5-1.5 or 5.0-15.0",
    critical: "<0.5 or >15.0",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "H12",
    category: "H",
    name: "Transaction Velocity (7-day slope)",
    formula: "linear_slope(total_txns, 7d)",
    meaning: "Commerce direction-of-travel",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I1",
    category: "I",
    name: "Games Discovery Rate (unique)",
    formula: "clicked_games_unique / dau_ga * 100",
    meaning: "% of users entering games section",
    healthy: ">=40",
    warning: "20-40",
    critical: "<20",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I2",
    category: "I",
    name: "Games Total Clicks per Day",
    formula: "avg_unique_user_games",
    meaning: "Aggregate click volume in games",
    healthy: "Growing with DAU",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I3",
    category: "I",
    name: "Clicks per Games-Clicker",
    formula: "avg_unique_user_games / clicked_games_unique",
    meaning: "Depth of games engagement per user",
    healthy: ">=2.5",
    warning: "1.5-2.5",
    critical: "<1.5",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I4",
    category: "I",
    name: "Games Click Density (per view)",
    formula: "avg_unique_user_games / total_homepage_views",
    meaning: "Games activity per homepage view",
    healthy: ">=1.0",
    warning: "0.4-1.0",
    critical: "<0.4",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I5",
    category: "I",
    name: "Games Stickiness",
    formula:
      "(clicked_games_unique / dau_ga) * (avg_unique_user_games / clicked_games_unique) * 100",
    meaning: "Combined discovery × depth",
    healthy: ">=100",
    warning: "60-100",
    critical: "<60",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I6",
    category: "I",
    name: "Games-to-STW Win Conversion",
    formula: "stw_winners / clicked_games_unique * 100",
    meaning: "% of games-visitors who win STW",
    healthy: ">=30",
    warning: "15-30",
    critical: "<15",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I7",
    category: "I",
    name: "Games-to-Earn Conversion (BNRY)",
    formula: "(bnry_earned_stw + bnry_earned_fando) / clicked_games_unique",
    meaning: "Avg tokens earned per games-visitor",
    healthy: "Stable",
    warning: "Drifting",
    critical: "Drift >30%",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I8",
    category: "I",
    name: "STW Lower-Bound Win Rate",
    formula: "stw_winners / dau_ga * 100",
    meaning: "Daily STW winners as % of audience",
    healthy: "15-35",
    warning: "5-15",
    critical: "<5",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I9",
    category: "I",
    name: "Games Click Trend (7-day)",
    formula: "linear_slope(avg_unique_user_games, 7d)",
    meaning: "Games engagement direction",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I10",
    category: "I",
    name: "Access Pass Daily Adoption",
    formula: "access_pass_buyers / dau_ga * 100",
    meaning: "% daily paid-pass users",
    healthy: "2-8",
    warning: "0.5-2",
    critical: "<0.5",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I11",
    category: "I",
    name: "Access Pass 30-day Cohort",
    formula: "sum(unique access_pass_buyers, 30d)",
    meaning: "Total paid-pass monthly pool",
    healthy: "Growing",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I12",
    category: "I",
    name: "Quest Engagement Depth",
    formula: "txns_quest / dau_ga",
    meaning: "Quests per user (can be >1)",
    healthy: ">=0.5",
    warning: "0.2-0.5",
    critical: "<0.2",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I13",
    category: "I",
    name: "Feature Coverage",
    formula: "count(features used by >=5% DAU) / total_features * 100",
    meaning: "Are all features pulling weight?",
    healthy: ">=80",
    warning: "50-80",
    critical: "<50",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I14",
    category: "I",
    name: "Premium-Tier Penetration",
    formula: "cumulative_access_pass_buyers / cumulative_DAU * 100",
    meaning: "Lifetime conversion to paid pass",
    healthy: ">=5",
    warning: "1-5",
    critical: "<1",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "I15",
    category: "I",
    name: "Multi-Feature User Concentration",
    formula: "sessions_with_games_OR_txns_OR_AP / total_homepage_views * 100",
    meaning: "Multi-feature engagement",
    healthy: ">=60",
    warning: "30-60",
    critical: "<30",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "J1",
    category: "J",
    name: "Economy Velocity",
    formula: "bnry_redeemed_total / bnry_earned_total",
    meaning: "Closed-loop circulation",
    healthy: "0.3-0.7",
    warning: "0.1-0.3 or 0.7-0.95",
    critical: "<0.1 or >1.0",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "J2",
    category: "J",
    name: "Outstanding-to-Daily-Earn Ratio",
    formula: "outstanding / bnry_earned_total",
    meaning: "Days of issuance unspent",
    healthy: "30-90",
    warning: "90-180",
    critical: ">180",
    unit: "days",
    views: ["global", "country", "workspace"],
  },
  {
    id: "J3",
    category: "J",
    name: "Inflation Risk Index",
    formula: "(sum(bnry_earned, 30d) / sum(bnry_redeemed, 30d)) - 1",
    meaning: "Excess issuance",
    healthy: "-0.2 to +0.2",
    warning: "+0.2 to +0.5",
    critical: ">+0.5",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "J4",
    category: "J",
    name: "Spending Mechanism Efficiency",
    formula: "count(redeem_sources with >=15% share)",
    meaning: "Spend sinks working?",
    healthy: ">=2",
    warning: "1",
    critical: "0",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "J5",
    category: "J",
    name: "Earning Mechanism Efficiency",
    formula: "count(earn_sources with >=10% share)",
    meaning: "Diverse earn mix",
    healthy: "4-5",
    warning: "3",
    critical: "1-2",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "J6",
    category: "J",
    name: "BNRY per User-Day (lifetime proxy)",
    formula: "sum(bnry_earned, 30d) / sum(dau_ga, 30d)",
    meaning: "Per-user-day earn rate",
    healthy: "Stable ±15%",
    warning: "Drift ±15-30%",
    critical: "Drift >30%",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "J7",
    category: "J",
    name: "Token Velocity",
    formula: "sum(bnry_redeemed, 30d) / avg(outstanding, 30d)",
    meaning: "How fast supply circulates",
    healthy: "0.3-1.0",
    warning: "0.1-0.3",
    critical: "<0.1 (frozen)",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "J8",
    category: "J",
    name: "Token Economy Health Score",
    formula: "0.4*band(G2) + 0.3*band(F7) + 0.2*band(G9) + 0.1*band(J3)",
    meaning: "0-100 composite",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "K1",
    category: "K",
    name: "DAU 30-Day Trajectory",
    formula: "linear_slope(dau_ga, 30d)",
    meaning: "Long-term growth",
    healthy: "Positive slope",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "K2",
    category: "K",
    name: "Engagement 30-Day Trajectory",
    formula: "linear_slope(dau_ga * avg_session_sec * sessions_per_user, 30d)",
    meaning: "Engagement depth trend",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "K3",
    category: "K",
    name: "BNRY Earn 30-Day Trajectory",
    formula: "linear_slope(bnry_earned_total, 30d)",
    meaning: "Issuance momentum",
    healthy: "Positive (per-user stable)",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "K4",
    category: "K",
    name: "BNRY Redeem 30-Day Trajectory",
    formula: "linear_slope(bnry_redeemed_total, 30d)",
    meaning: "Spend momentum",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "K5",
    category: "K",
    name: "Transaction Volume Trajectory",
    formula: "linear_slope(total_txns, 30d)",
    meaning: "Commerce momentum",
    healthy: "Positive",
    warning: "Flat",
    critical: "Negative",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "K6",
    category: "K",
    name: "WoW Acceleration",
    formula: "wow_growth[t] - wow_growth[t-7]",
    meaning: "Growth accelerating or decaying",
    healthy: "Positive (compounding)",
    warning: "Flat",
    critical: "Negative (decay)",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "K7",
    category: "K",
    name: "30-Day Volatility (CoV)",
    formula: "stdev(dau_ga, 30d) / mean(dau_ga, 30d)",
    meaning: "Predictability",
    healthy: "<15",
    warning: "15-30",
    critical: ">30",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "K8",
    category: "K",
    name: "DAU vs Baseline Z-score",
    formula: "(dau_ga - mean(dau_ga, 30d)) / stdev(dau_ga, 30d)",
    meaning: "Anomaly detection",
    healthy: "-1 to +2",
    warning: "-2 to -1 or +2 to +3",
    critical: "<-2 or >+3",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L1",
    category: "L",
    name: "OneWave Vitality Index",
    formula:
      "0.22*band(B4) + 0.18*band(D1) + 0.13*band(C2) + 0.13*band(G2) + 0.09*band(A2) + 0.09*band(N15) + 0.05*band(O2) + 0.06*band(P14) + 0.05*band_inv(P9)",
    meaning: "Headline platform health 0-100",
    healthy: ">=70",
    warning: "45-70",
    critical: "<45",
    unit: "",
    views: ["global"],
  },
  {
    id: "L2",
    category: "L",
    name: "Token Economy Health Score",
    formula: "= J8",
    meaning: "Closed-loop diagnostic 0-100",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L3",
    category: "L",
    name: "Engagement Depth Score",
    formula: "0.4*band(C2) + 0.3*band(C3) + 0.3*band(H7)",
    meaning: "How deeply users engage 0-100",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L4",
    category: "L",
    name: "Acquisition Vitality",
    formula: "0.5*band(A2) + 0.3*band(A5) + 0.2*band(A6)",
    meaning: "Acquisition pipeline 0-100",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L5",
    category: "L",
    name: "Commerce Conversion Score",
    formula: "0.4*band(H2) + 0.3*band(H5) + 0.3*band(H3)",
    meaning: "Commerce engagement 0-100",
    healthy: ">=60",
    warning: "35-60",
    critical: "<35",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L6",
    category: "L",
    name: "Retention Strength Index",
    formula: "0.5*band(B4) + 0.3*band(D1) + 0.2*band(D4)",
    meaning: "Long-term value signal 0-100",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L7",
    category: "L",
    name: "Feature Health Index",
    formula: "= I13",
    meaning: "All features working? 0-100",
    healthy: ">=80",
    warning: "50-80",
    critical: "<50",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L8",
    category: "L",
    name: "Game Funnel Score",
    formula: "0.3*band(I1) + 0.25*band(I6) + 0.25*band(I3) + 0.2*band(I4)",
    meaning: "Game-loop effectiveness 0-100",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L9",
    category: "L",
    name: "Premium Layer Index",
    formula: "0.6*band(I10) + 0.4*band(I14)",
    meaning: "Subscription tier health 0-100",
    healthy: ">=60",
    warning: "30-60",
    critical: "<30",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L10",
    category: "L",
    name: "Composite Risk Score",
    formula: "weighted(M1 + D7 + J3 + F8 + H10)",
    meaning: "Aggregate risk 0-100 (lower=better)",
    healthy: "<25",
    warning: "25-50",
    critical: ">50",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L11",
    category: "L",
    name: "Cohort Retention Index",
    formula: "0.3*band(N10) + 0.3*band(N11) + 0.25*band(N12) + 0.15*band(N13)",
    meaning: "Multi-horizon retention 0-100",
    healthy: ">=60",
    warning: "35-60",
    critical: "<35",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "L12",
    category: "L",
    name: "Paid Monetization Health Score",
    formula: "= O10",
    meaning: "Real-money revenue layer 0-100",
    healthy: ">=60",
    warning: "35-60",
    critical: "<35",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "M1",
    category: "M",
    name: "Daily Anomaly Count",
    formula: "count(metrics where |zscore| > 2 vs 30d baseline)",
    meaning: "Unusual metrics today",
    healthy: "0-1",
    warning: "2-3",
    critical: ">=4",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "M2",
    category: "M",
    name: "Per-Source Earn Drift",
    formula: "max(per-source share DoD change)",
    meaning: "Sudden mechanism shift",
    healthy: "<5",
    warning: "5-15",
    critical: ">15",
    unit: "pp",
    views: ["global", "country", "workspace"],
  },
  {
    id: "M3",
    category: "M",
    name: "DAU Spike Detection",
    formula: "z_score(dau_ga, 30d)",
    meaning: "Spike or crash",
    healthy: "-1 to +2",
    warning: "-2 to -1 or +2 to +3",
    critical: "<-2 or >+3",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "M4",
    category: "M",
    name: "Redemption Imbalance",
    formula: "G2[t] - avg(G2, 30d)",
    meaning: "Spend pattern deviation",
    healthy: "±10",
    warning: "±10-25",
    critical: "±>25",
    unit: "pp",
    views: ["global", "country", "workspace"],
  },
  {
    id: "M5",
    category: "M",
    name: "Concentration Risk",
    formula: "max(F8, H10)",
    meaning: "Worst single-point-of-failure share",
    healthy: "<50",
    warning: "50-70",
    critical: ">70",
    unit: "%",
    views: ["global", "country", "workspace"],
  },
  {
    id: "M6",
    category: "M",
    name: "Trend Reversal Flags",
    formula: "count(metrics where 7d trend reversed sign)",
    meaning: "Direction-of-travel breaks",
    healthy: "0-2",
    warning: "3-5",
    critical: ">=6",
    unit: "",
    views: ["global", "country", "workspace"],
  },
  {
    id: "P1",
    category: "P",
    name: "Country DAU",
    formula: "sum(dau_ga) across workspaces in country",
    meaning: "Daily active users in country",
    healthy: "Growing WoW per country",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["country"],
  },
  {
    id: "P2",
    category: "P",
    name: "Country MAU (30d)",
    formula: "sum(mau_d30) across workspaces in country",
    meaning: "Monthly active in country",
    healthy: "Growing MoM",
    warning: "Flat",
    critical: "Declining",
    unit: "",
    views: ["country"],
  },
  {
    id: "P3",
    category: "P",
    name: "Country DAU/MAU Stickiness",
    formula: "country_DAU / country_MAU * 100",
    meaning: "Stickiness within country",
    healthy: ">=20",
    warning: "10-20",
    critical: "<10",
    unit: "%",
    views: ["country"],
  },
  {
    id: "P4",
    category: "P",
    name: "Country Share of Global DAU",
    formula: "country_DAU / global_DAU * 100",
    meaning: "% of OneWave audience this country contributes",
    healthy: "Stable ±15%",
    warning: "Drift ±15-30%",
    critical: "Drift >30%",
    unit: "%",
    views: ["country"],
  },
  {
    id: "P5",
    category: "P",
    name: "Country Engagement Intensity",
    formula:
      "(country_DAU * country_avg_session * country_sessions_per_user) / country_MAU",
    meaning: "Engagement depth per country",
    healthy: "Stable ±15%",
    warning: "Drift ±15-30%",
    critical: "Drift >30%",
    unit: "",
    views: ["country"],
  },
  {
    id: "P6",
    category: "P",
    name: "Country BNRY Economy Velocity",
    formula: "country_bnry_redeemed / country_bnry_earned",
    meaning: "Token economy health per country",
    healthy: "0.3-0.7",
    warning: "0.1-0.3 or 0.7-0.95",
    critical: "<0.1 or >1.0",
    unit: "",
    views: ["country"],
  },
  {
    id: "P7",
    category: "P",
    name: "Country Paid Conversion Rate",
    formula: "country_txns_topup / country_DAU * 100",
    meaning: "Paid-user conversion per country",
    healthy: "3-10",
    warning: "0.5-3",
    critical: "<0.5",
    unit: "%",
    views: ["country"],
  },
  {
    id: "P8",
    category: "P",
    name: "Country Health Composite",
    formula:
      "0.3*band(P3) + 0.25*band(D1 per country) + 0.2*band(P6) + 0.15*band(P7) + 0.1*band(A2 per country)",
    meaning: "Single 0-100 country score",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["country"],
  },
  {
    id: "P9",
    category: "P",
    name: "Cross-Country Variance (CoV)",
    formula:
      "stdev(country health composites) / mean(country health composites)",
    meaning: "How divergent are countries?",
    healthy: "<25",
    warning: "25-50",
    critical: ">50",
    unit: "%",
    views: ["global"],
  },
  {
    id: "P10",
    category: "P",
    name: "Geographic Concentration Index (HHI)",
    formula: "sum((country share of global DAU)^2) * 10000",
    meaning: "Market concentration (Herfindahl-Hirschman)",
    healthy: "<2500",
    warning: "2500-5000",
    critical: ">5000",
    unit: "",
    views: ["global"],
  },
  {
    id: "P11",
    category: "P",
    name: "Top-Country Dominance",
    formula: "max(country share of global DAU) * 100",
    meaning: "Largest country's % of total audience",
    healthy: "<40",
    warning: "40-60",
    critical: ">60",
    unit: "%",
    views: ["global"],
  },
  {
    id: "P12",
    category: "P",
    name: "Country Tier Distribution",
    formula: "count_in_tier(country_composites) / total_countries",
    meaning: "% of countries in healthy tier",
    healthy: ">=50% in green",
    warning: "30-50% in green",
    critical: "<30% in green",
    unit: "",
    views: ["global"],
  },
  {
    id: "P13",
    category: "P",
    name: "Country Growth Differential",
    formula: "max(country MoM growth) - min(country MoM growth)",
    meaning: "Spread between fastest and slowest country",
    healthy: "<15",
    warning: "15-30",
    critical: ">30",
    unit: "pp",
    views: ["global"],
  },
  {
    id: "P14",
    category: "P",
    name: "Geographic Resilience Index",
    formula:
      "count(countries with positive 30d DAU trajectory) / total_active_countries * 100",
    meaning: "% of countries trending up",
    healthy: ">=70",
    warning: "40-70",
    critical: "<40",
    unit: "%",
    views: ["global"],
  },
  {
    id: "P15",
    category: "P",
    name: "Country Revenue Concentration",
    formula: "max(country share of global topup BNRY) * 100",
    meaning: "Largest country's % of paid revenue",
    healthy: "<45",
    warning: "45-65",
    critical: ">65",
    unit: "%",
    views: ["global"],
  },
  {
    id: "L13",
    category: "L",
    name: "Geographic Health Score",
    formula:
      "0.3*band(P14) + 0.25*band(P12) + 0.2*band_inv(P9) + 0.15*band_inv(P11) + 0.1*band_inv(P13)",
    meaning: "Cross-market performance 0-100",
    healthy: ">=65",
    warning: "40-65",
    critical: "<40",
    unit: "",
    views: ["global"],
  },
];

/** Metrics that apply to a single partner (workspace) view. */
export function workspaceMetrics(): AtlasMetric[] {
  return ATLAS_METRICS.filter((m) => m.views.includes("workspace"));
}

export const METRICS_BY_CATEGORY = new Map<string, AtlasMetric[]>(
  ATLAS_METRIC_CATEGORIES.map((c) => [
    c.id,
    ATLAS_METRICS.filter((m) => m.category === c.id),
  ]),
);
