/**
 * @vitest-environment happy-dom
 */
import { html, render } from 'lit';
import { describe, expect, test } from 'vitest';

import { ChatMessageAssistant } from './assistant';

describe('ChatMessageAssistant loading state', () => {
  test('ChatMessageAssistant > given transmitting reply has no content yet > renders loading state', () => {
    const container = document.createElement('div');
    const assistant = {
      isLast: true,
      status: 'transmitting',
      item: {
        id: 'message-1',
        role: 'assistant',
        content: '',
        createdAt: new Date(0).toISOString(),
      },
      renderHeader: () => html``,
      renderContent: () => html``,
    } as unknown as ChatMessageAssistant;

    render(
      (ChatMessageAssistant.prototype as any).render.call(assistant),
      container
    );

    expect(container.querySelector('ai-loading')).not.toBeNull();
  });

  test('ChatMessageAssistant > given settled independent reply has content > renders save-as-doc button', () => {
    const container = document.createElement('div');
    const assistant = Object.create(
      ChatMessageAssistant.prototype
    ) as ChatMessageAssistant;
    Object.defineProperties(assistant, {
      isLast: { value: true, writable: true },
      status: { value: 'success', writable: true },
      host: { value: { children: [] }, writable: true },
      session: { value: null, writable: true },
      independentMode: { value: true, writable: true },
      savedDocId: { value: null, writable: true },
      savedDocMessageKey: { value: null, writable: true },
      savingDocMessageKey: { value: null, writable: true },
      retry: { value: () => {}, writable: true },
      notificationService: { value: {}, writable: true },
      item: {
        value: {
          id: 'message-1',
          role: 'assistant',
          content: '# Draft proposal\n\nGenerated by AI.',
          createdAt: new Date(0).toISOString(),
        },
        writable: true,
      },
    });

    render(
      (ChatMessageAssistant.prototype as any).renderEditorActions.call(
        assistant
      ),
      container
    );

    expect(
      container.querySelector('[data-testid="ai-save-as-doc-button"]')
    ).not.toBeNull();
  });

  test('ChatMessageAssistant > given doc compose result and text delta > saves composed markdown', () => {
    const assistant = Object.create(
      ChatMessageAssistant.prototype
    ) as ChatMessageAssistant;
    Object.defineProperty(assistant, 'item', {
      value: {
        id: 'message-1',
        role: 'assistant',
        content: '',
        createdAt: new Date(0).toISOString(),
        streamObjects: [
          {
            type: 'text-delta',
            textDelta: 'Document created successfully.',
          },
          {
            type: 'tool-result',
            toolCallId: 'tool-1',
            toolName: 'doc_compose',
            args: { title: 'Launch Brief' },
            result: {
              title: 'Launch Brief',
              markdown: '# Launch Brief\n\nThis is the generated document.',
              wordCount: 7,
            },
          },
        ],
      },
      writable: true,
    });

    const payload = (
      ChatMessageAssistant.prototype as any
    ).getSaveAsDocPayload.call(assistant);

    expect(payload).toEqual({
      markdown: '# Launch Brief\n\nThis is the generated document.',
      title: 'Launch Brief',
    });
  });

  test('ChatMessageAssistant > given plan text > renders agent plan card', () => {
    const container = document.createElement('div');
    const assistant = Object.create(
      ChatMessageAssistant.prototype
    ) as ChatMessageAssistant;
    Object.defineProperty(assistant, 'item', {
      value: {
        id: 'message-1',
        role: 'assistant',
        content:
          'Plan:\n1. Search workspace sources.\n2. Draft the update.\n3. Save as doc.',
        createdAt: new Date(0).toISOString(),
      },
      writable: true,
    });

    render(
      (ChatMessageAssistant.prototype as any).renderAgentPlanCard.call(
        assistant
      ),
      container
    );

    expect(
      container.querySelector('[data-testid="ai-agent-plan-card"]')
    ).not.toBeNull();
    expect(container.textContent).toContain('Search workspace sources.');
  });

  test('ChatMessageAssistant > given tool stream objects > renders execution timeline', () => {
    const container = document.createElement('div');
    const assistant = Object.create(
      ChatMessageAssistant.prototype
    ) as ChatMessageAssistant;
    Object.defineProperty(assistant, 'item', {
      value: {
        id: 'message-1',
        role: 'assistant',
        content: '',
        createdAt: new Date(0).toISOString(),
        streamObjects: [
          {
            type: 'tool-result',
            toolCallId: 'tool-1',
            toolName: 'docHybridSearch',
            args: { query: 'launch plan' },
            result: { results: [] },
          },
          {
            type: 'tool-result',
            toolCallId: 'tool-2',
            toolName: 'docUpdate',
            args: { docId: 'doc-1' },
            result: {
              type: 'awaiting-approval',
              approvalId: 'approval-1',
            },
          },
        ],
      },
      writable: true,
    });

    render(
      (ChatMessageAssistant.prototype as any).renderToolTimeline.call(
        assistant
      ),
      container
    );

    expect(
      container.querySelector('[data-testid="ai-tool-timeline"]')
    ).not.toBeNull();
    expect(
      container.querySelector('[data-status="awaiting-approval"]')
    ).not.toBeNull();
    expect(container.textContent).toContain('Searched workspace');
  });
});
